apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls 
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls 
  issuerRef:
    name: vaultwarden-letsencrypt
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
  - <path:argocd/data/argocd-vault-plugin/vaultwarden#DOMAIN>
