apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app.kubernetes.io/name: "vaultwarden"
