apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-storage-pvc
  namespace: vaultwarden
  labels:
    type: local
    app: vaultwarden
spec:
  storageClassName: vaultwarden-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi